from app.models.types import ImageMeta, ApiMetaResponse

DUMMY_IMAGES: list[ImageMeta] = [
    {
        "image_id": "R-0001",
        "created_at": "2024-01-15",
        "status": "FINAL_UPDATED",
        "quality_level": "HIGH",
        "integrity_status": "OK",
        "dedup_hit": False,
        "duplicate_of": None,
        "original_image_url": "gs://bucket/R-0001/original.jpg",
        "thumb_image_url": "gs://bucket/R-0001/thumb.jpg",
        "final_receipt": {
            "purchased_at": "2024-01-14",
            "total_amount": 3200,
            "store_name": "コンビニA",
            "payment_method": "現金",
        },
        "ocr_receipt_info": None,
    },
    {
        "image_id": "R-0002",
        "created_at": "2024-01-16",
        "status": "OCR_DONE",
        "quality_level": "MEDIUM",
        "integrity_status": "WARN",
        "dedup_hit": False,
        "duplicate_of": None,
        "original_image_url": "gs://bucket/R-0002/original.jpg",
        "thumb_image_url": "gs://bucket/R-0002/thumb.jpg",
        "ocr_receipt_info": {
            "purchased_at": "2024-01-15",
            "total_amount": 1500,
            "store_name": "スーパーB",
            "payment_method": "クレジット",
        },
        "final_receipt": None,
    },
    {
        "image_id": "R-0003",
        "created_at": "2024-01-17",
        "status": "INGESTED",
        "quality_level": "LOW",
        "integrity_status": "UNSET",
        "dedup_hit": False,
        "duplicate_of": None,
        "original_image_url": "gs://bucket/R-0003/original.jpg",
        "thumb_image_url": "gs://bucket/R-0003/thumb.jpg",
        "ocr_receipt_info": {
            "purchased_at": "2024-01-16",
            "total_amount": 8400,
            "store_name": "レストランC",
            "payment_method": "電子マネー",
        },
        "final_receipt": None,
    },
    {
        "image_id": "R-0004",
        "created_at": "2024-01-18",
        "status": "INGESTED",
        "quality_level": "UNSET",
        "integrity_status": "UNSET",
        "dedup_hit": True,
        "duplicate_of": "R-0003",
        "original_image_url": "gs://bucket/R-0004/original.jpg",
        "thumb_image_url": "gs://bucket/R-0004/thumb.jpg",
        "ocr_receipt_info": {
            "purchased_at": "2024-01-17",
            "total_amount": 640,
            "store_name": "カフェD",
            "payment_method": "現金",
        },
        "final_receipt": None,
    },
    {
        "image_id": "R-0005",
        "created_at": "2024-01-19",
        "status": "DROPPED",
        "quality_level": "HIGH",
        "integrity_status": "OK",
        "dedup_hit": False,
        "duplicate_of": None,
        "original_image_url": "gs://bucket/R-0005/original.jpg",
        "thumb_image_url": "gs://bucket/R-0005/thumb.jpg",
        "final_receipt": {
            "purchased_at": "2024-01-18",
            "total_amount": 12000,
            "store_name": "百貨店E",
            "payment_method": "クレジット",
        },
        "ocr_receipt_info": None,
    },
]

DUMMY_META: ApiMetaResponse = {
    "version": "0.1.0-test",
    "env": "test",
}
