from app.models.types import ImageMeta, ApiMetaResponse

DUMMY_IMAGES: list[ImageMeta] = [
    {
        "image_id": "R-0001",
        "upload_date": "2024-01-15",
        "purchase_date": "2024-01-14",
        "total_amount": 3200,
        "store_name": "コンビニA",
        "payment_method": "現金",
        "status": "FINAL_UPDATED",
        "quality_level": "HIGH",
        "consistency_status": "OK",
        "is_duplicate": False,
        "parent_image_id": None,
        "etag": None,
    },
    {
        "image_id": "R-0002",
        "upload_date": "2024-01-16",
        "purchase_date": "2024-01-15",
        "total_amount": 1500,
        "store_name": "スーパーB",
        "payment_method": "クレジット",
        "status": "OCR_DONE",
        "quality_level": "MEDIUM",
        "consistency_status": "WARN",
        "is_duplicate": False,
        "parent_image_id": None,
        "etag": None,
    },
    {
        "image_id": "R-0003",
        "upload_date": "2024-01-17",
        "purchase_date": "2024-01-16",
        "total_amount": 8400,
        "store_name": "レストランC",
        "payment_method": "電子マネー",
        "status": "INGESTED",
        "quality_level": "LOW",
        "consistency_status": "UNSET",
        "is_duplicate": False,
        "parent_image_id": None,
        "etag": None,
    },
    {
        "image_id": "R-0004",
        "upload_date": "2024-01-18",
        "purchase_date": "2024-01-17",
        "total_amount": 640,
        "store_name": "カフェD",
        "payment_method": "現金",
        "status": "INGESTED",
        "quality_level": "UNSET",
        "consistency_status": "UNSET",
        "is_duplicate": True,
        "parent_image_id": "R-0003",
        "etag": None,
    },
    {
        "image_id": "R-0005",
        "upload_date": "2024-01-19",
        "purchase_date": "2024-01-18",
        "total_amount": 12000,
        "store_name": "百貨店E",
        "payment_method": "クレジット",
        "status": "DROPPED",
        "quality_level": "HIGH",
        "consistency_status": "OK",
        "is_duplicate": False,
        "parent_image_id": None,
        "etag": None,
    },
]

DUMMY_META: ApiMetaResponse = {
    "version": "0.1.0-test",
    "env": "test",
}
